USE LibraryBear;

INSERT INTO book VALUES (1,'The Amazing Book Is Not on Fire: The World of Dan and Phil','Dan Howell','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51gJ82I7bZL.jpg',NULL);
INSERT INTO book VALUES (2,'Twilight Tenth Anniversary/Life and Death Dual Edition','Stephenie Meyer','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51fT2LOwQgL.jpg',NULL);
INSERT INTO book VALUES (3,'Harry Potter Paperback Box Set (Books 1-7)','J. K. Rowling','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51BBTJaU6QL.jpg',NULL);
INSERT INTO book VALUES (4,'Library of Souls: The Third Novel of Miss Peregrine\'s Peculiar Children','Ransom Riggs','Teen & Young Adult','http://ecx.images-amazon.com/images/I/516ETg2nrlL.jpg',NULL);
INSERT INTO book VALUES (5,'Carry On','Rainbow Rowell','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51aT-%2BHwVqL.jpg',NULL);
INSERT INTO book VALUES (6,'Winter (The Lunar Chronicles)','Marissa Meyer','Teen & Young Adult','http://ecx.images-amazon.com/images/I/41SSIYbE2LL.jpg',NULL);
INSERT INTO book VALUES (7,'The Maze Runner Series (Maze Runner)','James Dashner','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51GcSiLFYeL.jpg',NULL);
INSERT INTO book VALUES (8,'Michael Vey 5: Storm of Lightning','Richard Paul Evans','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51DJ%2B4lX5YL.jpg',NULL);
INSERT INTO book VALUES (9,'Harry Potter and the Sorcerer\'s Stone','J.K. Rowling','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51PxQCRCx0L.jpg',NULL);
INSERT INTO book VALUES (10,'The Death Cure (Maze Runner, Book Three)','James Dashner','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51hrwXHI7jL.jpg',NULL);
INSERT INTO book VALUES (11,'The Rose Society (A Young Elites Novel)','Marie Lu','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51%2BFlUlFz5L.jpg',NULL);
INSERT INTO book VALUES (12,'The Giver (Giver Quartet)','Lois Lowry','Teen & Young Adult','http://ecx.images-amazon.com/images/I/61-cJVGfj6L.jpg',NULL);
INSERT INTO book VALUES (13,'Six of Crows','Leigh Bardugo','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51LYZqzZcNL.jpg',NULL);
INSERT INTO book VALUES (14,'The Scorch Trials (Maze Runner, Book 2)','James Dashner','Teen & Young Adult','http://ecx.images-amazon.com/images/I/518YN1zzOjL.jpg',NULL);
INSERT INTO book VALUES (15,'Girl Online: On Tour','Zoe Sugg','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51f%2BIJeCgdL.jpg',NULL);
INSERT INTO book VALUES (16,'The Maze Runner (Book 1)','James Dashner','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51P9MJrBQCL.jpg',NULL);
INSERT INTO book VALUES (17,'Journey to Star Wars: The Force Awakens Lost Stars','Claudia Gray','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51gF3dYpeTL.jpg',NULL);
INSERT INTO book VALUES (18,'Paper Towns','John Green','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51hgkNew%2BXL.jpg',NULL);
INSERT INTO book VALUES (19,'Rush Revere and the First Patriots: Time-Travel Adventures With Exceptional Americans','Rush Limbaugh','Teen & Young Adult','http://ecx.images-amazon.com/images/I/517Vc9Jy0oL.jpg',NULL);
INSERT INTO book VALUES (20,'Miss Peregrine\'s Home for Peculiar Children (Miss Peregrine\'s Peculiar Children)','Ransom Riggs','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51xgGEKd6oL.jpg',NULL);
INSERT INTO book VALUES (21,'Rush Revere and the Brave Pilgrims: Time-Travel Adventures with Exceptional Americans','Rush Limbaugh','Teen & Young Adult','http://ecx.images-amazon.com/images/I/514izSXQ1uL.jpg',NULL);
INSERT INTO book VALUES (22,'Happily Ever After: Companion to the Selection Series (The Selection Novella)','Kiera Cass','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51L1Q0kK9RL.jpg',NULL);
INSERT INTO book VALUES (23,'The Fate of Ten (Lorien Legacies)','Pittacus Lore','Teen & Young Adult','http://ecx.images-amazon.com/images/I/61Dgk0A3COL.jpg',NULL);
INSERT INTO book VALUES (24,'Rush Revere and the Star-Spangled Banner','Rush Limbaugh','Teen & Young Adult','http://ecx.images-amazon.com/images/I/618X4EoMgBL.jpg',NULL);
INSERT INTO book VALUES (25,'The Kill Order (Maze Runner, Prequel) (The Maze Runner Series)','James Dashner','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51QsOn2IGRL.jpg',NULL);
INSERT INTO book VALUES (26,'The Hunger Games Trilogy: The Hunger Games / Catching Fire / Mockingjay','Suzanne Collins','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51dvPNSo82L.jpg',NULL);
INSERT INTO book VALUES (27,'Harry Potter And The Chamber Of Secrets','J. K. Rowling','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51jNORv6nQL.jpg',NULL);
INSERT INTO book VALUES (28,'Illuminae (The Illuminae Files)','Amie Kaufman','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51vpagSvAYL.jpg',NULL);
INSERT INTO book VALUES (29,'Eleanor & Park','Rainbow Rowell','Teen & Young Adult','http://ecx.images-amazon.com/images/I/41yMNepSxpL.jpg',NULL);
INSERT INTO book VALUES (30,'Queen of Shadows (Throne of Glass)','Sarah J. Maas','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51r%2By3Ey6jL.jpg',NULL);
INSERT INTO book VALUES (31,'The 5th Wave: The First Book of the 5th Wave Series','Rick Yancey','Teen & Young Adult','http://ecx.images-amazon.com/images/I/519kWfgQqqL.jpg',NULL);
INSERT INTO book VALUES (32,'Hollow City: The Second Novel of Miss Peregrine\'s Peculiar Children','Ransom Riggs','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51RP7pNqzCL.jpg',NULL);
INSERT INTO book VALUES (33,'Waterfire Saga, Book Three Dark Tide','Jennifer Donnelly','Teen & Young Adult','http://ecx.images-amazon.com/images/I/5176eL1ZA1L.jpg',NULL);
INSERT INTO book VALUES (34,'The Boy\'s Body Book: Third Edition: Everything You Need to Know for Growing Up YOU','Kelli Dunham','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51RNn6LfRhL.jpg',NULL);
INSERT INTO book VALUES (35,'Harry Potter and the Prisoner of Azkaban','J.K. Rowling','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51gY5jzz3NL.jpg',NULL);
INSERT INTO book VALUES (36,'Divergent Series Ultimate Four-Book Box Set: Divergent, Insurgent, Allegiant, Four','Veronica Roth','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51qtn8zJVnL.jpg',NULL);
INSERT INTO book VALUES (37,'Judy Blume\'s Fudge Box Set','Judy Blume','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51X%2BJOXIfpL.jpg',NULL);
INSERT INTO book VALUES (38,'Harry Potter and the Deathly Hallows (Book 7)','J. K. Rowling','Teen & Young Adult','http://ecx.images-amazon.com/images/I/5128ATd9dSL.jpg',NULL);
INSERT INTO book VALUES (39,'The Heir (The Selection)','Kiera Cass','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51a5h1OlkvL.jpg',NULL);
INSERT INTO book VALUES (40,'Red Queen','Victoria Aveyard','Teen & Young Adult','http://ecx.images-amazon.com/images/I/41VTPDCAq5L.jpg',NULL);
INSERT INTO book VALUES (41,'The Fault in Our Stars','John Green','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51VlKD1aucL.jpg',NULL);
INSERT INTO book VALUES (42,'Thirteen Reasons Why','Jay Asher','Teen & Young Adult','http://ecx.images-amazon.com/images/I/411MJMpTseL.jpg',NULL);
INSERT INTO book VALUES (43,'Allegiant (Divergent Series)','Veronica Roth','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51AXNYr9hkL.jpg',NULL);
INSERT INTO book VALUES (44,'The Boy in the Striped Pajamas (Young Reader\'s Choice Award - Intermediate Division)','John Boyne','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51BS6FjTqqL.jpg',NULL);
INSERT INTO book VALUES (45,'The Rest of Us Just Live Here','Patrick Ness','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51dDM7po-yL.jpg',NULL);
INSERT INTO book VALUES (46,'The Game of Lives (The Mortality Doctrine, Book Three)','James Dashner','Teen & Young Adult','http://ecx.images-amazon.com/images/I/512B30QVD0L.jpg',NULL);
INSERT INTO book VALUES (47,'Nimona','Noelle Stevenson','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51m5E%2BGsZhL.jpg',NULL);
INSERT INTO book VALUES (48,'A Smart Girl\'s Guide: Drama, Rumors & Secrets: Staying True to Yourself in Changing Times (Smart Girl\'s Guides)','Nancy Holyoke','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51m1OlQCMsL.jpg',NULL);
INSERT INTO book VALUES (49,'The Giver Quartet boxed set','Lois Lowry','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51LkGVu9TnL.jpg',NULL);
INSERT INTO book VALUES (50,'The Infinite Sea: The Second Book of the 5th Wave','Rick Yancey','Teen & Young Adult','http://ecx.images-amazon.com/images/I/51c%2BwRUGMvL.jpg',NULL);
